# Linear Algebra for Machine Learning

## Introduction

**Linear algebra** is a core mathematical foundation for machine learning, as most datasets and models are represented using vectors and matrices. It allows efficient computation, data manipulation and optimization, making complex tasks manageable.

- **Data in ML is represented as:**
   - vectors --> features
   - Matrices --> datasets
- **Operations** like dot product, matrix multiplication and transformations power ML algorithms.
- **Key concepts** such as eigenvalues, eigenvectors and decompositions simplify dimensionality reduction, optimization and training.

# Section 1 : Fundamental Concepts in Linear Algebra for Machine Learning

## 1) Vectors

### Definition

> **Vectors** are quantities that have both magnitude and direction, often represented as arrows in space.
>
 #### **From computer science perspective :**
> > vectors are ordered lists of numbers
>
> >  $\vec{v} = [1, 2, 3]$
>
 #### **From physics perspective :**
> > vectors are arrows pointing in space. What defines a given vector is its length and the direction it's pointing, but as long as those two facts are the same you can move it around and it's still the same vector.
> >
> >  <img src="physics_vectors.PNG" align="left" style="margin-right: 10px;" />  Vectors that live in a flat plane are two-dimensional, and those sitting in the broader space that we live in are three-dimensional.
>


>
>
#### **From a mathmatical perspective :**
> > Math generalizes both of these views, basically saying that a vector can be anything where there's a sensible notion of adding two vectors and multiplying a vector by a numbe.
> >
> 
 #### **linear algebra**
> > 
> 
> > <img src="vectors_pov.PNG"  style="margin-right: 10px;" />
> 
> **The usefulness of linear algebra** has less to do with either one of these views than it does with **the ability to translate back and forth between them**. It gives the data-analyst a nice way to conceptualize many lists of numbers in a visual way, which can seriously clarify patterns in the data and give a global view of what certain operations do.


Reference for this lesson : https://www.3blue1brown.com/lessons/vectors/

In [1]:
import numpy as np
v = np.array([25, 50000, 3]) # a customer: age, income, tenure


### Vectorization

#### Why are vectors so important in Machine Learning?
>Vectors allow us to represent data in a mathematical form that computers can process efficiently.
Instead of processing one value at a time, we can process an entire vector of values at once. This idea is called **vectorization.**

#### Vectorization 
>is the process of performing the same operation on an entire vector (or matrix) instead of looping through each element individually

#### For example, suppose we have the ages of five people:

In [ ]:
ages = [20, 25, 18, 30, 22]

#### If we want to add one year to everyone's age, we could use a loop:

In [ ]:
new_ages = []

for age in ages:
    new_ages.append(age + 1)

#### With NumPy, we can treat the whole list as a vector:

In [ ]:
import numpy as np

ages = np.array([20, 25, 18, 30, 22])
new_ages = ages + 1

#  result : [21 26 19 31 23]

#### Why Vectorization?
Machine Learning models often work with **millions** of numbers.

Instead of processing every pixel one by one, we represent all of them as vectors or matrices and apply mathematical operations to the whole dataset simultaneously.

This makes Machine Learning:

- Much faster.
- More memory efficient.
- Easier to write and understand.
- Able to take advantage of optimized libraries like NumPy, which are implemented in low-level languages such as C.

## 2) Matrices: a full dataset (samples × features)

### Why Mtricies ? 

>Machine Learning models are trained on entire datasets, not just one sample.
>
>Instead of processing one vector at a time, **we organize all samples into a matrix.** This allows algorithms to perform computations on the whole dataset efficiently using vectorized operations.

### Representation

A matrix used for tabular data has **two dimensions**:

- **Rows (\(m\))**
- **Columns (\(n\))**

Its size is written as an **\(m \times n\)** matrix, meaning:

- **\(m\)** = number of rows (samples)
- **\(n\)** = number of columns (features)

### Structure of Tabular Matrices

- **Rows (\(m\))**: Represent individual items, records, or samples (horizontal lines).
- **Columns (\(n\))**: Represent variables, features, or attributes (vertical lines).
- **Order**: Matrix dimensions are always written as **rows first**, followed by **columns**.

In [2]:
X = np.array([[25, 50000, 3],
 [40, 80000, 10],
 [33, 62000, 5]])
print(X.shape) # (3, 3): 3 samples, 3 features

(3, 3)


## 3) The dot product and how models predict with it

### What is  Dot Product

The **dot product** is an operation between two vectors. It multiplies their corresponding elements and then adds the results together, producing a **single scalar value**.


### Mathematically:

$$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i
$$

For example:

```python
import numpy as np

features = np.array([25, 50000, 3])
weights = np.array([0.1, 0.0002, 1.5])

prediction = np.dot(features, weights)

print(prediction)
```

Output:

```text
17.0
```

The calculation is:

$$
(25 \times 0.1) + (50000 \times 0.0002) + (3 \times 1.5)
$$

$$
= 2.5 + 10 + 4.5 = 17.0
$$


### Why is the dot product important in Machine Learning?

The dot product is one of the **most fundamental operations** in Machine Learning. It combines the input features with their corresponding weights to produce a prediction.

For a linear model, the prediction is computed as:

$$
\text{prediction} = \mathbf{x} \cdot \mathbf{w} + b
$$

where:

- **$\mathbf{x}$** is the feature vector.
- **$\mathbf{w}$** is the weight vector learned by the model.
- **$b$** is the bias term.

This is exactly how models such as **Linear Regression** and **Logistic Regression** compute their output before making a prediction.

In [ ]:
features = np.array([25, 50000, 3])
weights = np.array([0.1, 0.0002, 1.5])
prediction = np.dot(features, weights) # 2.5 + 10 + 4.5 = 17.0

### Summary

> The dot product measures the weighted sum of the input features. Since many Machine Learning models rely on the equation
>
> $$
> \text{prediction} = \mathbf{x} \cdot \mathbf{w} + b,
> $$
>
> understanding the dot product is essential for understanding how these models make predictions

## 4) Matrix multiplication and the shape-matching rule


**Matrix multiplication** extends the idea of the dot product to entire datasets. Instead of computing the prediction for one sample at a time, it computes predictions for **all samples simultaneously**.

For matrix multiplication, the dimensions must follow this rule:

$$
(m \times n) \times (n \times p) = (m \times p)
$$

The **inner dimensions** must match. If they do not, matrix multiplication is not possible.

For example:

- A matrix of shape **(2, 3)** can be multiplied by a matrix or vector of shape **(3, 1)** or **(3,)**.
- The result will have shape **(2, 1)** or **(2,)**, meaning one output for each sample.

### Example, with code

In [2]:
import numpy as np

# Feature matrix (2 samples, 3 features)
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10]
])

# Weight vector (3 features)
w = np.array([0.1, 0.0002, 1.5])

# Compute predictions for all samples
predictions = X @ w

print(predictions)

[17. 35.]



Output:
```text
[17.0 33.5]
```

The shapes are:
- **Feature matrix:** `(2, 3)`
- **Weight vector:** `(3,)`
- **Output predictions:** `(2,)`

Each row of `X` is multiplied with the weight vector using the **dot product**, producing one prediction for each sample.


### Why is matrix multiplication important in Machine Learning?

Machine Learning models are trained on datasets containing **thousands or even millions of samples**. Computing predictions one sample at a time would be inefficient.

Matrix multiplication allows us to:

- Compute predictions for the entire dataset in a single operation.
- Take advantage of optimized numerical libraries such as **NumPy**.
- Significantly improve speed and efficiency through vectorized computations.




### Understanding Shapes

One of the most common errors in Machine Learning is a **shape mismatch**.

For matrix multiplication to work:

$$
(m \times n) \times (n \times p)
$$

the **inner dimensions** must be equal.

For example:

| Left Matrix | Right Matrix | Valid? | Result Shape |
|-------------|--------------|:------:|--------------|
| `(2, 3)` | `(3,)` | Yes | `(2,)` |
| `(100, 20)` | `(20,)` | Yes | `(100,)` |
| `(5, 4)` | `(4, 2)` | Yes | `(5, 2)` |
| `(2, 3)` | `(2,)` | No | Shape mismatch |


### Summary

> Matrix multiplication applies the **dot product** to every row of a dataset at once, allowing Machine Learning models to generate predictions for all samples efficiently. Understanding matrix shapes is essential because matrix multiplication only works when the inner dimensions match.

# Section 2 : Hands-on Lap

## Step 1: Represent three data samples as a (3 × features) NumPy matrix.

In [5]:
import numpy as np

# Each row is a sample, each column is a feature ( ID , age , GPA)
X = np.array([
      [202278697, 23, 3.5],
    [202374791, 21, 3.8],
    [202470987, 20, 3.2]])

print(X)
print(X.shape)

[[2.02278697e+08 2.30000000e+01 3.50000000e+00]
 [2.02374791e+08 2.10000000e+01 3.80000000e+00]
 [2.02470987e+08 2.00000000e+01 3.20000000e+00]]
(3, 3)


## Step 2: Compute the dot product of one sample vector with a weight vector by hand, then verify it with np.dot.



### Sample vector:

$x = [2, 3, 4, 5]$

### Weight vector:

$w = [4, 5, 6, 7]$

### Calculations

The dot product is calculated by multiplying corresponding elements and adding the results:


$x \cdot w = (2 \times 4) + (3 \times 5) + (4 \times 6) + (5 \times 7)$


$= 8 + 15 + 24 + 35$

$
= 82
$

Therefore:


$x \cdot w = 82$


In [6]:
import numpy as np

# Sample vector 1 x 4
x = np.array([2, 3, 4, 5])

# Weight vector 1 x 4
w = np.array([4, 5, 6, 7])

result = np.dot(x, w)
print(result)

82


## Step 3: Use matrix multiplication (@) to produce a prediction for all three samples at once.


In [7]:
import numpy as np

# Feature matrix (3 samples, 4 features)
X = np.array([
    [2, 3, 4, 5],
    [1, 6, 2, 8],
    [4, 2, 7, 3]
])

# Weight vector (4 features)
w = np.array([4, 5, 6, 7])

# Matrix multiplication to compute predictions for all samples
predictions = X @ w

print(predictions)

[ 82 102  89]


## Step 4: Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it occurred and how to fix it.

In [16]:
import numpy as np

# Feature matrix (4 samples, 4 features)
X = np.array([
    [2, 3, 4, 5],
    [1, 6, 2, 8],
    [4, 2, 7, 3],
    [4, 2, 7, 3]])

# weight vector (3 weights)
w = np.array([4, 5, 6])

predictions = X @ w
print(predictions)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

### Explaining the error:

For each feature in the matrix,  there should be a corresponding weight. Meaning, in order for the dot product to be successful, the number of, columns in the first the Victor should match or/ be the same number of rows in the matrix or dataset.
However, there was a mismatch where we had three column Victor and four rows matrix. In order to fix that, we  only have to add an additional weight in the first victor.

``` python
# Feature matrix (4 samples, 4 features)
X = np.array([
    [2, 3, 4, 5],
    [1, 6, 2, 8],
    [4, 2, 7, 3],
    [4, 2, 7, 3]])

# weight vector (4 weights)
w = np.array([4, 5, 6, 4])

predictions = X @ w
print(predictions)

```