In [3]:
import numpy as np

# Section 1 : Experements and Concepts

### 1) Creating Arrays

In [8]:

one_D_arr = np.array([1, 2, 3])    # 1D Array

two_D_arr = np.array([[1, 2, 3], [4, 5, 6]])    # 2D Array

three_D_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3D Array 

four_D_arr = np.array([[1,2,3,4] , [1,2,3,4], [1,2,3,4], [1,2,3,4]])   # creating a 4x4 size array from 4 lists

print(one_D_arr)
print()
print(two_D_arr)
print()
print(three_D_arr)
print()
print(four_D_arr)


[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


>To check the number of dimention use the attribute  `ndim`  that returns an integer that tells us how many dimensions the array have.
> To check the data type of the array elements, use the `dtype` attribute, which returns the data type stored in the array.

In [7]:
print('the dimrntion of the array is: ' , four_D_arr.ndim)    
print(four_D_arr.dtype)


the dimrntion of arr is:  2
int64


### 2) NumPy Indexing

Indexing is used to access **individual elements** in a NumPy array. Like Python lists, NumPy uses **zero-based indexing**, meaning the first element has index `0`, the second has index `1`, and so on.

 
> **Access 1-D Arrays:** use a single index to access an element.

| Syntax | Description |
|--------|-------------|
| `arr[0]` | First element |
| `arr[2]` | Third element |
| `arr[-1]` | Last element |

> **Access 2-D Arrays :** use the format arr[row, column]

In [15]:
print('3ed element on the list: ',one_D_arr[2])                                   #1D indexint
print('2nd element on 1st row: ', two_D_arr[0, 1])    #2D indexint

3ed element on the list:  3
2nd element on 1st row:  2


### 3) Slicing
>- **to slice we follow this logic : arr[ row , column ]**
>- for each row/ column we can specify [ start:end , start:end ]
>- the **start** is always **included** and the **end** is **excluded**

In [74]:
print("Extract the middle 2X2 square:")
print(nump_array[1:3, 1:3])
print()

print("Extract a 3X3 square:")
print(nump_array[1:4, 1:4])  # or nump_array[0:3, 0:3]
print()

print("Extract the 2 columns in the middle:")
print(nump_array[0:4, 1:3])
print()

print("Extract the 3rd row:")
print(nump_array[1, :])
print()

Extract the middle 2X2 square:
[[ 6  7]
 [10 11]]

Extract a 3X3 square:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]

Extract the 2 columns in the middle:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Extract the 3rd row:
[5 6 7 8]



# **Section 2 : Hands-on Lap**

## Step 1: Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.

#### Method 1: creating an array, filling it with numbers from 1-16 using a nested loop, and then converting it to a numpy array
> note: using nested loops isn't idel for this course but I'm adding this method for practicing python syntax more

In [29]:
arr2 = []
count = 1
for x in range(4):
    row = []
    for y in range(4):
        row.append(count)
        count+=1
    arr2.append(row)
arr3 = np.array(arr2)
    
print(arr3)
print('The shape of the array is :' , arr3.shape)
print('The data type og the array is: ' , arr3.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The shape of the array is : (4, 4)
The data type og the array is:  int64


#### Method 2 : using numpy functions arange() and reshape()

####  Reshaping arrays
>- Reshaping means changing the shape of an array.
>- The shape of an array is the number of elements in each dimension.
>- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [30]:
nump_array = np.arange(1,17).reshape(4,4)
print(nump_array)
print('The shape of the array is :' , nump_array.shape)
print('The data type og the array is: ' , nump_array.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The shape of the array is : (4, 4)
The data type og the array is:  int64


## Step 2: Use slicing to extract the second column and the last row.

In [44]:
print(nump_array)   # the array we are working with for this exercise

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Extracting the second column 

In [40]:
print(nump_array[: , 1:2])

[[ 2]
 [ 6]
 [10]
 [14]]


#### Extracting the last row 

In [43]:
print(nump_array[3 , :])

[13 14 15 16]


## Step 3: Use a boolean mask to select all values greater than the array's mean.

In [82]:
print(nump_array.mean()) 
print(nump_array[nump_array > 8]) 

8.5
[ 9 10 11 12 13 14 15 16]


## Step 4: Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [77]:
print('array before addition :')
print(nump_array)
print()

print('array after addition :')
one_Dimentiion_matrix = np.array([3,3,3,3])
print(nump_array + one_Dimentiion_matrix)

array before addition :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

array after addition :
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
